In [13]:
import requests
url="https://books.toscrape.com/"
res=requests.get(url)

In [14]:
res.status_code

200

In [15]:
with open("scraped_data/book.html","w",encoding="utf-8") as f:
    f.write(res.text)

In [16]:
from bs4 import BeautifulSoup
with open("scraped_data/book.html","r") as f:
    html_content=f.read()
soup=BeautifulSoup(html_content,"html.parser")

In [62]:
# Find all books
books = soup.find_all("article", class_="product_pod")

all_books = []

# Rating conversion dictionary
rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

for book in books:

    # Title
    title = book.find("h3").find("a").get("title")

    # Price
    price = book.find("p", class_="price_color").get_text(strip=True)

    # Remove the pound sign and encoding characters
    price = price.replace("£", "")
    price = price.replace("Ã‚Â", "")
    price = float(price)

    # Availability
    availability = book.find("p",class_="instock availability").get_text(strip=True)

    # Rating
    rating = book.find("p", class_="star-rating").get("class")[1]
    rating = rating_map[rating]

    # Store data
    all_books.append({
        "Title": title,
        "Price": price,
        "Availability": availability,
        "Rating": rating
    })

In [66]:
# Create DataFrame
import pandas as pd
df = pd.DataFrame(all_books)

df.head()

                                   Title  Price Availability  Rating
0                   A Light in the Attic  51.77     In stock       3
1                     Tipping the Velvet  53.74     In stock       1
2                             Soumission  50.10     In stock       1
3                          Sharp Objects  47.82     In stock       4
4  Sapiens: A Brief History of Humankind  54.23     In stock       5

In [76]:
# sort 
df.sort_values("Title",inplace=True)
df.reset_index(inplace=True)

In [80]:
df.drop(columns="index",inplace=True)

In [82]:
df

,Title,Price,Availability,Rating
0,A Light in the Attic,51.77,In stock,3
1,It's Only the Himalayas,45.17,In stock,2
2,Libertarianism for Beginners,51.33,In stock,2
3,Mesaerion: The Best Science Fiction Stories 18...,37.59,In stock,1
4,Olio,23.88,In stock,1
5,Our Band Could Be Your Life: Scenes from the A...,57.25,In stock,3
6,Rip it Up and Start Again,35.02,In stock,5
7,Sapiens: A Brief History of Humankind,54.23,In stock,5
8,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,In stock,5
9,Set Me Free,17.46,In stock,5
10,Shakespeare's Sonnets,20.66,In stock,4
11,Sharp Objects,47.82,In stock,4
12,Soumission,50.10,In stock,1
13,"Starving Hearts (Triangular Trade Trilogy, #1)",13.99,In stock,2
14,The Black Maria,52.15,In stock,1
15,The Boys in the Boat: Nine Americans and Their...,22.60,In stock,4
16,The Coming Woman: A Novel Based on the Life of...,17.93,In stock,3
17,The Dirty Little Secrets of Getting Your Dream...,33.34,In stock,4
18,The Requiem Red,22.65,In stock,1
19,Tipping the Velvet,53.74,In stock,1

In [84]:
df.to_csv("cleaned_data/books_data_scraped.csv")