### Pandas Assignment

In [22]:
#Question 1
#load IRIS datased 
import pandas as pd
df=pd.read_csv("IRIS.csv")

#A

# first 10 rows
df.head(10)
#shape
df.shape
#data types
df.dtypes
df.describe()

#B

#petal length > 4.5
df[df["petal_length"]>4.5]
#species = "Iris-virginica"
df[df["species"]=="Iris-virginica"]

#C

#compute avg sepal length
df.groupby("species").agg(avg_sepal_length=("sepal_length","mean"))
#max petal witdth
df.groupby("species").agg(max_petal_width=("petal_width","max"))
#std dev of sepal width
df.groupby("species").agg(std_dev_sepal_w=("sepal_width","std"))

#D

#new column petal ratio
df=df.assign(petal_ratio=df["petal_length"]/df["petal_width"])
#avg petal ratio for each specie
df.groupby("species").agg(avg_petal_ratio=("petal_ratio","mean"))

                 avg_petal_ratio
species
Iris-setosa             7.078000
Iris-versicolor         3.242837
Iris-virginica          2.780662

In [40]:
#load TITANIC dataset
df=pd.read_csv("Titanic-Dataset.csv")

#A -  Display only columns: A. Name, Sex, Age, Fare, Survived
df[["Name","Sex","Age","Fare","Survived"]]

#B - Select passengers who:
# Are female and
# Fare > 30

df[(df["Sex"]=="female") & (df["Fare"]>30)]

#C - group by Pclass and ocmpute
# survival rate, average fare, average age

df.groupby("Pclass").agg(
    avg_fare=("Fare","mean"),
    avg_age=("Age","mean"),
    survival_rate=("Survived","mean")
)

         avg_fare    avg_age  survival_rate
Pclass
1       84.154687  38.233441       0.629630
2       20.662183  29.877630       0.472826
3       13.675550  25.140620       0.242363

In [27]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q